plugins:
  - jekyll-paginate
  - jekyll-titles-from-headings

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /blog

exclude:
  - kasper/
  - docs/

locale: "en-US"
title: "DownFlux"
description: "Design docs and tech writeups related to the DownFlux RTS"
url: "https://downflux.github.io/blog/"
domain_name: "https://downflux.github.io/blog/"

author: "Minke Zhang"

# jekyll-titles-from-headings
# Remove H1 headings from content since page.title renders it anyways.
titles_from_headings:
  enabled: true
  strip_title: true
  collections: true
