plugins:
  - jekyll-paginate
  - jekyll-redirect-from

  # Allows setting the H1 Markdown header as the page title.
  - jekyll-titles-from-headings

  # Allows per-post assets.
  - jekyll-postfiles

exclude:
  - docs/

markdown: kramdown
highlighter: rouge
logo: false
permalink: pretty

paginate: 15
paginate_path: "/page/:num/"

language: "en"
timezone: "America/Los_Angeles"
name: "DownFlux"
description: "Design docs and tech writeups related to the DownFlux RTS"

# jekyll-titles-from-headings
titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

defaults:
  -
    scope:
      path: ""
    values:
      author: minke
