plugins:
  - jekyll-paginate-v2
  - jekyll-redirect-from

  # Allows setting the H1 Markdown header as the page title.
  - jekyll-titles-from-headings

  # Allows per-post assets.
  - jekyll-postfiles

exclude:
  - third_party/

markdown: kramdown
highlighter: none
logo: false
permalink: pretty

language: 'en'
timezone: 'America/Los_Angeles'
title: 'DownFlux'
description: 'A Gamedev Blog'
url: https://blog.downflux.com

# jekyll-titles-from-headings
titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

# jekyll-paginate-v2
pagination:
  enabled: true
  collection: 'posts'
  per_page: 15
  permalink: '/page/:num/'
  sort_reverse: true
  title: ':title'

autopages:
  enabled: true
  tags:
    layouts: ['collection.html']
    title: ':tag'
    slugify:
      mode: default
      case: false
  collections:
    layouts: ['collection.html']
    title: ':col'
    slugify:
      mode: default
  categories:
    layouts: ['collection.html']
    title: ':cat'
    slugify:
      mode: default

defaults:
  -
    scope:
      path: ''
    values:
      author: minke
