plugins:
  - jekyll-paginate
markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /blog

excludes:
  - kasper/*
  - docs/*

name: "DownFlux Blog"
title: "DownFlux Blog"
description: "Archive of technical, API, unit, and balance design documentation."
url: "https://downflux.github.io/blog/"
domain_name: "https://downflux.github.io/blog/"

author: "Minke Zhang"
