plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-titles-from-headings
  - jekyll-postfiles

exclude:
  - kasper/
  - docs/

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
permalink: pretty

locale: "en-US"

name: "DownFlux"
description: "Design docs and tech writeups related to the DownFlux RTS"

# jekyll-titles-from-headings
# Remove H1 headings from content since page.title renders it anyways.
titles_from_headings:
  enabled: true
  strip_title: true
  collections: true
