name: Publish Blog

on:
  push:
    branches: [ main ]

jobs:
  publish:
    name: Publish Blog
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: helaili/jekyll-action@2.1.0
        with:
          token: ${{ secrets.JEKYLL_PAT }}
